import { Video, Play, Image as LucideImage, Sparkles, Wand2 } from 'lucide-react';
import Link from 'next/link';

export default function Home() {
  return (
    <div className="min-h-full flex flex-col p-16 animate-fade-in">
      {/* Hero Section */}
      <h1 className="font-serif text-6xl italic font-light mb-6 tracking-tight">
        Olá, Doutor.
      </h1>
      <div className="w-16 h-[2px] bg-[var(--accent-blue)] mb-8" />
      
      <p className="max-w-xl text-gray-400 text-lg leading-relaxed font-light mb-16">
        How can I assist your market positioning today? From content analysis to global campaign architectures, I am your dedicated digital jurist of marketing strategy.
      </p>

      {/* Quick Start Label */}
      <div className="flex items-center space-x-2 mb-8">
        <span className="text-[10px] uppercase tracking-[0.3em] text-gray-500 font-bold">Quick Start</span>
      </div>

      {/* Main Feature Card */}
      <div className="w-full max-w-4xl glass-panel p-12 flex flex-col items-center justify-center text-center border-none mb-8 bg-[rgba(30,32,38,0.6)]">
        <div className="p-4 bg-[rgba(178,204,255,0.1)] rounded-xl mb-6 text-[var(--accent-blue)]">
          <Video size={48} strokeWidth={1.5} />
        </div>
        <h3 className="font-serif text-3xl font-light mb-2">Roteiro pra Vídeo</h3>
        <p className="text-gray-400 text-sm max-w-md">
          Generate viral scripts for Reels, YouTube or TikTok.
        </p>
      </div>

      {/* Steps Grid */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 w-full max-w-4xl">
        <div className="glass-panel p-6 flex flex-col items-center text-center space-y-4">
          <div className="w-10 h-10 rounded-lg bg-[rgba(255,255,255,0.03)] flex items-center justify-center text-gray-400">
            <Video size={20} />
          </div>
          <p className="text-[10px] text-gray-500 font-medium leading-relaxed">
            1 - Grave um video falando o roteiro, mesmo desarrumado
          </p>
        </div>

        <div className="glass-panel p-6 flex flex-col items-center text-center space-y-4">
          <div className="w-10 h-10 rounded-lg bg-[rgba(255,255,255,0.03)] flex items-center justify-center text-gray-400">
            <LucideImage size={20} />
          </div>
          <p className="text-[10px] text-gray-500 font-medium leading-relaxed">
            2 - Selecione uma foto pra ser animada como video
          </p>
        </div>

        <div className="glass-panel p-6 flex flex-col items-center text-center space-y-4">
          <div className="w-10 h-10 rounded-lg bg-[rgba(255,255,255,0.03)] flex items-center justify-center text-gray-400">
            <Sparkles size={20} />
          </div>
          <p className="text-[10px] text-gray-500 font-medium leading-relaxed">
            3 - Acesse o Kling e siga as instruções do tutorial
          </p>
        </div>

        <Link href="/instrucoes-kling" className="bg-[var(--accent-blue)] hover:bg-[var(--accent-blue-hover)] rounded-xl p-6 flex flex-col items-center justify-center text-black transition-all">
          <div className="w-10 h-10 rounded-full border border-black/10 flex items-center justify-center mb-4">
            <Play size={20} fill="currentColor" />
          </div>
          <p className="text-[10px] uppercase font-bold tracking-widest">Acessar Tutorial</p>
        </Link>
      </div>

      {/* Footer Quote */}
      <div className="mt-12 text-[9px] uppercase tracking-[0.2em] text-gray-600 font-semibold">
        MARKET INSIGHTS GENERATED BY DIGITAL JURIST AI ARE SUBJECT TO STRATEGIC REVIEW.
      </div>
    </div>
  );
}
